### ISSUE TITLE
Problem in Eval.py?

### ISSUE THREAD

**Issue by AndRossi** [daiquocnguyen/CapsE#8]
Hi, thanks for developing CapsE.
I think that using capsule networks may be the next big thing in Link prediction!

I'm opening this issue because I have the impression that your evaluation strategy, implemented in `evalCapsE.py`, may suffer from the same controversies emerged in ConvKB under this issue:
https://github.com/daiquocnguyen/ConvKB/issues/5

Am I correct?

**Comment by dschaehi** [comment]
This problem is addressed in detail in the following paper:

Z. Sun, S. Vashishth, S. Sanyal, P. Talukdar, Y. Yang, A Re-evaluation of Knowledge Graph Completion Methods, ArXiv:1911.03903 [Cs]. (2019). http://arxiv.org/abs/1911.03903 (accessed November 14, 2019).

If the existence of the mentioned problem is true, then the authors should make this public somewhere (e.g., https://ml-retrospectives.github.io/). I think this is important to advance research in this area.

**Comment by daiquocnguyen** [comment]
I have answered this issue at https://github.com/daiquocnguyen/ConvKB/issues/5
